# -*- coding: utf-8 -*-
"""ColoringTextusingPython_Estocapio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oysCakg-ii-J5yy7fp5ZQ8g9TxvQrevk
"""

import nltk
nltk.download('words')
from nltk.corpus import words
real_words = words.words()
colored_object = {}
roygbiv = {
    "Red": "\033[0;31m",
    "Orange": "\033[38;2;255;170;0m" ,
    "Yellow": "\033[0;33m",
    "Green": "\033[0;32m",
    "Blue": "\033[0;34m" ,
    "Indigo": "\033[36m" ,
    "Violet": "\033[0;35m",
        }
reset = "\033[0m"
choices = ["Coloring an Object", "Printing Colored Object", "Deleting Object", "Quit the Application"]

print('''Welcome to A Hue Ko Na!
Choose an option: ''')
while True:
    num = 0
    for option in choices:
        print(f"[{num + 1}]{choices[num]}")
        num = num + 1
    option = (input("Enter your choice (1/2/3/4): "))

    if option == '1':
      while True:
        chosen_object = input("Enter the name of the object you want to color: ")
        if chosen_object in colored_object:
            print("Object is already colored.")
        elif chosen_object not in real_words:
            print("Please type in real words.")
            break
        else:
            print("Choose a color among the ROYGBIV colors:")
            for color_name in roygbiv.keys():
                color_code = roygbiv[color_name]
                print(f"🖼️{color_code}{color_name}{reset}")
            color_name = input("Choose a color among the ROYGBIV colors: ").capitalize()
            if color_name in roygbiv:
                colored_object[chosen_object] = color_name
                painted_object = f"{roygbiv[color_name]}{chosen_object}{reset} is now {roygbiv[color_name]}{color_name}{reset}. \n👾👾👾👾👾👾👾👾👾👾👾"
                print(painted_object)
                break
            else:
                print("Invalid color choice. Please choose a color from the list.")
    elif option == '2':
      if colored_object:
        print("Printing colored objects:")
        for chosen_object, color_name in colored_object.items():
              painted_object = f"{roygbiv[color_name]}{chosen_object}{reset} is now {roygbiv[color_name]}{color_name}{reset}."
              print(painted_object)
      else:
         print("No colored objects yet.")
    elif option == '3':
      while True:
        delete_object = input(f"Enter the object you want to delete: ")
      if delete_object in colored_object:
          to_delete = f"{roygbiv[colored_object[delete_object]]}{delete_object}{reset}."
          colored_object.pop(delete_object)
          print(f"{to_delete} has been deleted.")
          break
      else:
          print("Please choose an item you want to delete from the printed list.")
    elif option == '4':
        print("Thank you for using A Hue Ko na! See you next time!")
        break
    else:
        print("Please choose among the choices.")

!pip install nltk