# -*- coding: utf-8 -*-
"""Estocapio_Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBwQDbCm4sXCIMCARFJKjtQWi8JJArbU
"""

import math

#Declaration of Variables
choices = ["Square", "Rectangle", "Triangle", "Trapezoid", "Hexagon", "Octagon", "Circle", "Exit"]
red = "\033[31m"
orange = "\033[38;2;255;170;0m"
yellow = "\033[0;33m"
green = "\033[0;32m"
blue = "\033[0;34m"
cyan = "\033[0;36m"
violet = "\033[0;35m"
reset = "\033[0m"

#Define the  functions and the formulas for the shapes
def area_of_square(square_side):
  return square_side**2

def area_of_rectangle(rectangle_length, rectangle_width):
  return rectangle_length * rectangle_width

def area_of_triangle(triangle_base, triangle_height):
  return ((triangle_base * triangle_height)/2)

def area_of_trapezoid(trapezoid_base1, trapezoid_base2, trapezoid_height):
  return (((trapezoid_base1 + trapezoid_base1) * trapezoid_height)/2)

def area_of_hexagon(hexagon_side):
  return ((3 * math.sqrt(3) / 2) * hexagon_side **2)

def area_of_octagon(octagon_side):
  return (2 * (1 + math.sqrt(2)) * octagon_side ** 2)

def area_of_circle(radius):
  return (math.pi * radius)

# Instructions for the user once they open the application.
print('''Welcome to Shape Atlas: Area Shape Calculator!
Here, you can calculate the area of certain
shapes by providing the needed inputs!

If you wish to exit the application when you're
done with your computations, you can exit
the application by inputing the number [8]''')
print('⬛ ⬜ ' * 10)

while True:
    # This code block is a loop that will keep on printing until the user chooses to exit the application.
    num = 0

    for shape in choices:

        print(f"[{num + 1}] {choices[num]}")
        num = num + 1

    print('⬛ ⬜ ' * 10)

    # The try-except code block will handle the 'ValueError' if the user will input a string instead of an integer
    try:
        app_options = int(input("Please choose among the numbers on which among the shapes you would like to compute the area : "))
    except ValueError:
        print("Please input the number corresponding to the shape you've chosen.")
        print('⬛ ⬜ ' * 10)
    else:
        if app_options == 1:
          #If the user chooses 1, they will be directed to compute the area of a square
            print("You've chosen to compute the area of the Square.")
            print(red + " ________ ")
            print(red +"|        |")
            print(red +"|        |")
            print(red +"|        |")
            print(red +"|________|" + reset)

             # A loop for the user to input their chosen measurement for the side of the square
            while True:
                try:
                    square_side = float(input("Please input the side of the square: "))
                except ValueError:
                    print("Sorry, the calculator cannot compute strings, try inputting numbers.")
                else:
                    if square_side < 0:
                        print("Please input a positive number.")
                    elif square_side == 0:
                        print("The measurement of the side cannot be zero.")
                    else:
                        print(f"The area of the square is: {area_of_square(square_side)}")

                        break
            print('⬛ ⬜ ' * 10)

        elif app_options == 2:
          #If the user chooses 2, they will be directed to compute the area of a rectangle
          print("You've chosen to compute the area of the Rectangle.")
          print(orange + " ____________________ " )
          print(orange + "|                    |")
          print(orange + "|                    |")
          print(orange + "|____________________|" + reset)

          # A loop for the user to input their chosen measurement for the length of the rectangle
          while True:
            try:
              rectangle_length = float(input("Please input the length of the rectangle:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if rectangle_length < 0:
                print("Please input a positive number.")
              elif rectangle_length == 0:
                print("The measurement of the length cannot be zero..")
              else:
                break


          # A loop for the user to input their chosen measurement for the width of the rectangle
          while True:
            try:
              rectangle_width = float(input("Please input the width of the rectangle:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if rectangle_width < 0:
                print("Please input a positive number.")
              elif rectangle_width  == 0:
                print("The measurement of the width cannot be zero.")
              else:
                print(f"The area of the rectangle is: {(area_of_rectangle(rectangle_length, rectangle_width))}")
                print('⬛ ⬜ ' * 10)
                # The function will now be called to be print the computed area of the rectangle
                break

        elif app_options == 3:
          #If the user chooses 3, they will be directed to compute the area of a triangle
          print("You've chosen to compute the area of the Triangle.")
          print(yellow + "   /\\   ")
          print(yellow + "  /  \\  ")
          print(yellow + " /    \\ ")
          print(yellow + "/______\\" + reset)

          # A loop for the user to input their chosen measurement for the height of the triangle
          while True:
            try:
              triangle_height = float(input("Please input the height of the triangle:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if triangle_height < 0:
                print("Please input a positive number.")
              elif triangle_height == 0:
                print("The measurement of the height cannot be zero.")
              else:
                break

          # A loop for the user to input their chosen measurement for the base of the triangle
          while True:
            try:
              triangle_base = float(input("Please input the width of the triangle:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if triangle_base < 0:
                print("Please input a positive number.")
              elif triangle_base == 0:
                print("The measurement of the base cannot be zero..")
              else:
                print(f"The area of the triangle is: {(area_of_triangle(triangle_base, triangle_height))}")
                print('⬛ ⬜ ' * 10)
                # The function will now be called to be print the computed area of the triangle
                break

        elif app_options == 4:
          #If the user chooses 4, they will be directed to compute the area of a trapezoid
          print("You've chosen to compute the area of the Trapezoid.")
          print(green + "   ______")
          print(green + "  /      \\")
          print(green + " /        \\")
          print(green + "/__________\\" + reset)

          # A loop for the user to input their chosen measurement for the base1 of the trapezoid
          while True:
            try:
              trapezoid_base1 = float(input("Please input the base 1 of the trapeziod:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if trapezoid_base1 < 0:
                print("Please input a positive number.")
              elif trapezoid_base1 == 0:
                print("The measurement of the base cannot be zero..")
              else:
                break

          #  A loop for the user to input their chosen measurement for the base2 of the trapezoid
          while True:
            try:
              trapezoid_base2 = float(input("Please input the base 2 of the trapeziod:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if trapezoid_base2 < 0:
                print("Please input a positive number.")
              elif trapezoid_base2 == 0:
                print("The measurement of the base cannot be zero..")
              else:
                break

          # A loop for the user to input their chosen measurement for the height of the trapezoid
          while True:
            try:
              trapezoid_height = float(input("Please input the height of the trapezoid:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if trapezoid_height < 0:
                print("Please input a positive number.")
              elif trapezoid_height == 0:
                print("The measurement of the base cannot be zero..")
              else:
                print(f"The area of the trapezoid is: {(area_of_trapezoid(trapezoid_base1, trapezoid_base2, trapezoid_height))}")
                print('⬛ ⬜ ' * 10)
                # The function will now be called to be print the computed area of the trapezoid
                break

        elif app_options == 5:
          #If the user chooses 5, they will be directed to compute the area of a hexagon
          print("You've chosen to compute the area of the Hexagon.")
          print(blue + "   _______")
          print(blue + "  /       \\")
          print(blue + " /         \\")
          print(blue + " \         /")
          print(blue + "  \_______/" + reset)

          # A loop for the user to input their chosen measurement for the side of the hexagon
          while True:
            try:
              hexagon_side = float(input("Please input the side of the hexagon:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if hexagon_side < 0:
                print("Please input a positive number.")
              elif hexagon_side == 0:
                print("The measurement of the length cannot be zero..")
              else:
                print(f"The area of the hexagon is: {(area_of_hexagon(hexagon_side))}")
                print('⬛ ⬜ ' * 10)
                # The function will now be called to print the computed area of the hexagon
                break

        elif app_options == 6:
          #If the user chooses 6, they will be directed to compute the area of an octagon
          print("You've chosen to compute the area of the Octagon.")
          print(cyan + "   _______")
          print(cyan + "  /       \\")
          print(cyan + " /         \\")
          print(cyan + "|           |")
          print(cyan + "|           |")
          print(cyan + " \\         /")
          print(cyan + "  \\_______/" + reset)

          # A loop for the user to input their chosen measurement for the side of the octagon
          while True:
            try:
              octagon_side = float(input("Please input the side of the octagon:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if octagon_side < 0:
                print("Please input a positive number.")
              elif octagon_side == 0:
                print("The measurement of the length cannot be zero..")
              else:
                print(f"The area of the octagon is: {(area_of_octagon(octagon_side))}")
                print('⬛ ⬜ ' * 10)
                # The function will now be called to print the computed area of the octagon
                break

        elif app_options == 7:
          #If the user chooses 7, they will be directed to compute the area of a circle
          print("You've chosen to compute the area of the Circle")
          print(violet + "    *  *  *")
          print(violet + "  *         * ")
          print(violet + " *           * ")
          print(violet + " *           * ")
          print(violet + "  *         * ")
          print(violet + "    *  *  * " + reset)

          # A loop for the user to input their chosen measurement for the radius of the circle
          while True:
            try:
              radius = float(input("Please input the radius of the circle:  "))
            except ValueError:
                print("Sorry, the calculator cannot compute strings, try inputting numbers.")
            else:
              if radius < 0:
                print("Please input a positive number.")
              elif radius == 0:
                print("The measurement of the length cannot be zero..")
              else:
                print(f"The area of the Circle is: {(area_of_circle(radius))}")
                print('⬛ ⬜ ' * 10)
                # The function will now be called to print the computed area of the circle
                break

        elif app_options == 8:
          #If the user chooses 8, they will exit the calculator
          print("Thank you for using Shape Atlas: Area Shape Calculator!!")
          break
        else:
          #If the user chooses inputs something that isn't in the list, they will be instructed to input again
          print("Please choose among the choices.")